### ISSUE TITLE
Landing page formatting

### ISSUE THREAD

**Issue by jessbeutler** [hotosm/hotdocs#3]
1. "Read Documentation" button currently overlaps text.

![image](https://user-images.githubusercontent.com/36767434/66855238-e16dc380-ef50-11e9-91fe-96ea48d7e32f.png)

2. Page title and Markdown title are redundant. Change title (highlighted) to reflect markdown title "Welcome to the HOT Toolbox" or hide/remove.  
![image](https://user-images.githubusercontent.com/36767434/66855410-2a257c80-ef51-11e9-864f-4eadcddb5d76.png)

**Comment by russbiggs** [comment]
for item #2 this is based on the design spec where the main title is the name of the site. This title is to match the dropdown in the header bar etc. I agree that its nice to have customizable titles but it will require some sort of standard for the _index.md page to always include a top level h1 to introduce the page.  Is that something we can document and make clear to future documentation creators?
